## 1. What Is A Python Numpy Array?
You already read in the introduction that NumPy arrays are a bit like Python lists, but still very much different at the same time. For those of you who are new to the topic, let’s clarify what it exactly is and what it’s good for.

As the name kind of gives away, a NumPy array is a central data structure of the numpy library. The library’s name is actually short for “Numeric Python” or “Numerical Python”.

This already gives an idea of what you’re dealing with, right?

In other words, NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a huge amount of high-level mathematical functions operate on these matrices and arrays.

In [ ]:
#import numpy library
import numpy as np

In [ ]:
my_array = np.array([1,2,3,4,5])
my_2d_array = np.array([[1,2],[8,9]])
my_3d_array = np.arange(12).reshape(2,2,3)
# Print the array
print("1d_array: ")
print(my_array)

# Print the 2d array
print("2d_array: ")
print(my_2d_array)

# Print the 3d array
print("3d_array: ")
print(my_3d_array)

1d_array: 
[1 2 3 4 5]
2d_array: 
[[1 2]
 [8 9]]
3d_array: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
my_array.ndim

1

##  2. Data, shape, dtype
* The data pointer indicates the memory address of the first byte in the array,
* The data type or dtype pointer describes the kind of elements that are contained within the array,
* The shape indicates the shape of the array, and

In [ ]:
# Print out memory address
print(my_2d_array.data)

# Print out the shape of `my_array`
print(my_2d_array.shape)

# Print out the data type of `my_array`
print(my_2d_array.dtype)

# Print out the stride of `my_array`
#print(my_2d_array.strides)

(2, 2)
int64


## 3. Properties

In [ ]:
# Create an array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Create an array of zeros
np.zeros((2,3,5,4),dtype=np.int16)

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int16)

In [ ]:
# Create an array with random values
np.random.random((2,2))

array([[0.36535647, 0.03481817],
       [0.21979235, 0.64055615]])

In [ ]:
# Create an empty array
np.empty((3,2))


array([[2.45260273e-316, 6.89861352e-310],
       [5.39489646e-317, 5.39488065e-317],
       [1.02277546e-259, 6.89860508e-310]])

In [ ]:
# Create a full array
np.full((2,2),1)
#np.ones((2,2))

array([[1, 1],
       [1, 1]])

In [ ]:
# Create an array of evenly-spaced values
np.arange(10,25,5)

array([10, 15, 20])

In [ ]:
# Create an array of evenly-spaced values
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## 4. How NumPy Broadcasting Works
Before you go deeper into scientific computing, it might be a good idea to first go over what broadcasting exactly is: it’s a mechanism that allows NumPy to work with arrays of different shapes when you’re performing arithmetic operations.

To put it in a more practical context, you often have an array that’s somewhat larger and another one that’s somewhat smaller. Ideally, you want to use the smaller array multiple times to perform an operation (such as a sum, multiplication, etc.) on the larger array.

To do this, you use the broadcasting mechanism.

However, there are some rules if you want to use it. And, before you already sigh, you’ll see that these “rules” are very simple and kind of straightforward!

* First off, to make sure that the broadcasting is successful, the dimensions of your arrays need to be compatible. Two dimensions are compatible when they are equal. Consider the following example:

In [ ]:
# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.random.random((3,4))

# Check shape of `y`
print(y.shape)

# Add `x` and `y`
x + y

(3, 4)
(3, 4)


array([[1.10976705, 1.98287406, 1.88592967, 1.47504415],
       [1.66923744, 1.72471464, 1.8138191 , 1.00895459],
       [1.1294695 , 1.03357011, 1.81455922, 1.42187368]])

In [ ]:
# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.ones((1,4))

# Check shape of `y`
print(y)

# addition `x` and `y`
x + y

(3, 4)
[[1. 1. 1. 1.]]


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
x + 1

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
x * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
x/2

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [ ]:
print(x.shape)
y = np.arange(3).reshape(3,1)
print(y)
print(y.shape)

(3, 4)
[[0]
 [1]
 [2]]
(3, 1)


In [ ]:
x + y

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [ ]:
w = np.array([[1,2,3]])
print(w)
print(w.shape)
x = np.ones((4,3))
print(x)
print(x+w)

[[1 2 3]]
(1, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


## 5. How Do Array Mathematics Work?
* You’ve seen that broadcasting is handy when you’re doing arithmetic operations. In this section, you’ll discover some of the functions that you can use to do mathematics with arrays.

* As such, it probably won’t surprise you that you can just use +, -, *, / or % to add, subtract, multiply, divide or calculate the remainder of two (or more) arrays. However, a big part of why NumPy is so handy, is because it also has functions to do this. The equivalent functions of the operations that you have seen just now are, respectively, np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder().

* You can also easily do exponentiation and taking the square root of your arrays with np.exp() and np.sqrt(), or calculate the sines or cosines of your array with np.sin() and np.cos(). Lastly, its’ also useful to mention that there’s also a way for you to calculate the natural logarithm with np.log() or calculate the dot product by applying the dot() to your array.

In [ ]:
#Note : x*y and x.dot(y)
x = np.arange(9).reshape(3,3)
y = np.arange(3).reshape(3,1)
print("x :\n",x)
print("y :\n",y)
print("x*y = \n",x*y)
print("x.dot(y) = \n",x.dot(y))
print(np.dot(x,y))


x :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
y :
 [[0]
 [1]
 [2]]
x*y = 
 [[ 0  0  0]
 [ 3  4  5]
 [12 14 16]]
x.dot(y) = 
 [[ 5]
 [14]
 [23]]
[[ 5]
 [14]
 [23]]


* Something a little bit more advanced than subsetting, if you will, is slicing. Here, you consider not just particular values of your arrays, but you go to the level of rows and columns. You’re basically working with “regions” of data instead of pure “locations”.

You can see what is meant with this analogy in these code examples:

In [ ]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [ ]:
x[:]

array([1, 2, 3, 4, 5])

In [ ]:
x[0:4]

array([1, 2, 3, 4])

In [ ]:
x[:3]

array([1, 2, 3])

In [ ]:
x[-1:]

array([5])

## 6. How To Transpose Your Arrays
What transposing your arrays actually does is permuting the dimensions of it. Or, in other words, you switch around the shape of the array. Let’s take a small example to show you the effect of transposition:

In [ ]:
my_2d_array = np.arange(6).reshape(2,3)
# Print `my_2d_array`
print(my_2d_array)

[[0 1 2]
 [3 4 5]]


In [ ]:
# Transpose `my_2d_array`
print(np.transpose(my_2d_array))

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
# Or use `T` to transpose `my_2d_array`
print(my_2d_array.T)

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
print(my_2d_array.shape)
print(my_2d_array.T.shape)

(2, 3)
(3, 2)


In [ ]:
my_3d_array = np.arange(24).reshape(2,3,4)
print(my_3d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(np.transpose(my_3d_array,(2,1,0)))

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


## 7. Indexing
* Single element indexing

In [ ]:
x = np.arange(10)
print(x)
print(x[2])

print(x[-2])

[0 1 2 3 4 5 6 7 8 9]
2
8


* Multiple element indexing

In [ ]:
x.shape = (2,5) # now x is 2-dimensional
print(x)
x[1,3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


8

In [ ]:
x = np.arange(10)

In [ ]:
x[2:5]

array([2, 3, 4])

In [ ]:
x[:-7]

array([0, 1, 2])

In [ ]:
x[1:7:2]

array([1, 3, 5])

In [ ]:
y = np.arange(35).reshape(5,7)
print(y)
y[1:5:2,:3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7,  8,  9],
       [21, 22, 23]])

* Boolean or “mask” index arrays

In [ ]:
y = np.array([16,50,19,20,21,22])
b = y>20
print(b)

y[b]

[False  True False False  True  True]


array([50, 21, 22])

In [ ]:
y = np.arange(9).reshape(3,3)
print(y)
mask = np.array([0,1,1])
print(mask)
index = np.arange(3)
print(index)


y[index,mask] #[0,1,2],[0,1,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 1]
[0 1 2]


array([0, 4, 7])

* np.max, np.min, np.argmax, np.argmin

In [ ]:
a = np.array([[2,1,3,4,5],[4,3,8,6,7]])
print(a)

[[2 1 3 4 5]
 [4 3 8 6 7]]


In [ ]:
A = np.shape(a)[0]
print(A)

2


In [ ]:
row_max = np.max(a,1)
row_argmax = np.argmax(a,0)



print(row_max)  #np.array
print(col_max )
print(row_argmax)
print(col_argmax)

[5 8]
[4 3 8 6 7]
[1 1 1 1 1]
[1 1 1 1 1]


## 8. How To Join And Split Arrays
* You can also ‘merge’ or join your arrays. There are a bunch of functions that you can use for that purpose and most of them are listed below.



In [ ]:
my_array = np.array([1,2,3,4])
x = np.ones((4))

print(np.concatenate((my_array,x)))

[1. 2. 3. 4. 1. 1. 1. 1.]


In [ ]:
my_2d_array = np.ones((2,4))
# Stack arrays row-wise
print(np.vstack((my_array, my_2d_array)))

[[1. 2. 3. 4.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
my_resized_array = my_array.reshape((2,2))
# Stack arrays horizontally
print(np.hstack((my_resized_array, my_2d_array)))

[[1. 2. 1. 1. 1. 1.]
 [3. 4. 1. 1. 1. 1.]]


In [ ]:
# Stack arrays column-wise
print(np.column_stack((my_resized_array, my_2d_array)))

[[1. 2. 1. 1. 1. 1.]
 [3. 4. 1. 1. 1. 1.]]


## 9. Numpy Practices

### 9.1 Gaussian Jordan elimination

In [ ]:
def gausJordan(A,b):
    N = np.shape(b)[0]
    '''YOUR CODE HERE'''
    pass
    return (A,b)

def solve(A,b):
    '''YOUR CODE HERE'''
    pass
    return x

A = np.array([[1,1,1],[1,3,1],[1,1,2]], dtype='float')
b = np.array([[1], [3], [2]])
x = solve(A,b)
print(x)

In [ ]:
def gausJordan(A,b):

    # np.shape(b)= [3,1] trả về kích thước của ma trận B
    # np.shape(b)[0] trả về số hàng của ma trận
    # xác định số lượng phần tử trong vector b, thường đại diện cho số phương trình trong hệ phương trình tuyến tính.
    N = np.shape(b)[0]
    AB =

    # Tham số -1 trong reshape cho phép NumPy tự động tính toán kích thước phù hợp cho chiều đó dựa trên kích thước của chiều còn lại,
    # và 1 xác định số cột (ở đây là một cột).=> nôm na là chuyển tử ma trận ngang sang ma trận dọc
    # np.hstack là một hàm của NumPy dùng để ghép các mảng lại với nhau theo chiều ngang (tức là nối các cột lại với nhau).
    M = np.hstack((A, b.reshape(-1, 1)))
    # Nếu nhập vào là 1 ma trận n hàng 1 cột thì không cần reshape M = np.hstack(A, b)
    for i in range(N):
        # # Chuẩn hóa hàng thứ i sao cho các phần tử đường chéo chính trở thành 1
        M[i, :] = M[i, :] / M[i, i]

        # Eliminate the current column elements in other rows
        for j in range(N):
            if i != j:
                M[j, :] = M[j, :] - M[j, i] * M[i, :]

    # Ma trận A sau khi biến đối lấy từ tất cả các cột trừ cột cuối cùng của ma trận
    A = M[:, :-1]

    # vector b đã biến đổi là cột cuối cùng của ma trận M
    b = M[:, -1]
    pass
    return (A,b)

# Hàm này trả về giá trị nghiệm
def solve(A,b):
    A, b = gausJordan(A,b)
    x = b
    pass
    return x

A = np.array([[1,1,1],[1,3,1],[1,1,2]], dtype='float')
b = np.array([[1], [3], [2]])
x = solve(A,b)
print(x)

[-1.  1.  1.]


In [ ]:
import numpy as np

def gausJordan(A, b):
    N = np.shape(b)[0]
    M = np.hstack((A, b)) #M = np.hstack((A, b.reshape(-1, 1)))

    for i in range(N):
        # Chuẩn hóa hàng thứ i sao cho các phần tử đường chéo chính trở thành 1
        M[i, :] = M[i, :] / M[i, i]

        # Loại bỏ các phần tử trong cột i của các hàng khác
        for j in range(N):
            if i != j:
                M[j, :] = M[j, :] - M[j, i] * M[i, :]

    # Trả về ma trận A, b sau khi biến đối
    A = M[:, :-1]
    b = M[:, -1]
    return (A,b)

# Tách nghiệm
def solve(A, b):
    A, b = gausJordan(A, b)
    x = b
    return x

# test
A = np.array([[1,1,1],[1,3,1],[1,1,2]], dtype='float')
b = np.array([[1], [3], [2]])

# Giải hệ phương trình
x = solve(A, b)
print("Nghiệm:", x)

Nghiệm: [-1.  1.  1.]


### 9.2 Gradient Checking      $f(x)=4x^4+5x^3-2x^2+3x+7$


In [ ]:
def f(x):
    ''' Evaluate f(x)'''
    '''YOUR CODE HERE'''
    pass

def df(x):
    ''' Evaluate f'(x)'''
    '''YOUR CODE HERE'''
    pass

def gradient_check(x, h = 1e-5):
    ''' Evaluate f'(x)'''
    '''YOUR CODE HERE'''

    return rel_error

x = 0
#result should be 1e-11
print(gradient_check(x))



In [ ]:
# Định nghĩa các hàm
def f(x):
    return 4 * x**4 + 5 * x**3 - 2 * x**2 + 3 * x + 7

def df(x):
    return 16 * x**3 + 15 * x**2 - 4 * x + 3

def gradient_check(x, h=1e-5):
    # Tính gradient bằng cách số
    numerical_grad = (f(x + h) - f(x - h)) / (2 * h)

    # Tính gradient bằng cách giải tích
    analytical_grad = df(x)

    # In ra kết quả để so sánh
    print(f"Numerical Gradient: {numerical_grad}")
    print(f"Analytical Gradient: {analytical_grad}")

    # Kiểm tra sự khác biệt giữa hai kết quả
    rel_error = abs(numerical_grad - analytical_grad)

    return rel_error

x = 0
#result should be 1e-11
print(gradient_check(x))


Numerical Gradient: 3.0000000005081513
Analytical Gradient: 3
5.081512988169834e-10
